### ISSUE TITLE
choice with only one child

### ISSUE THREAD

**Issue by cfhaak** [bundesverfassung-oesterreich/bv-working-data#20]
https://github.com/bundesverfassung-oesterreich/bv-working-data/blob/77ddba3c6feffc0a7c813c48a26d2d2e924431a5/data/editions/bv_doc_id__2.xml#L2375

this seems not correct

**Comment by JKammerhofer** [comment]
Gerade ausgebessert, war natürlich <choice><del></del><add></add><choice>

**Comment by JKammerhofer** [comment]
deppates Github, macht aus dem Code ein Emoji:

>>>>> <choice><del></del><add></add></choice> <<<<<<<

**Comment by JKammerhofer** [comment]
`<choice><del></del><add></add></choice>`
