### ISSUE TITLE
Unidentifizierter Entwurf nach Linz- zweigliedriger Aufbau

### ISSUE THREAD

**Issue by sophiakry** [bundesverfassung-oesterreich/bv-working-data#21]
Der unidentifizierte Entwurf nach Linz folgt im Original einem zweispaltigen Aufbau. In der linken Spalte sind unter dem Titel "Linzer Entwurf" nur die Änderungen zu dem ursprünglichen Linzer Entwurf aufgezeigt; in der rechten Spalte steht unter dem Titel "Neuer Text" die neue Version des Textes. 
Wäre es möglich, hier ein zweigliedriges Format zu erzeugen, in welchen diese Gegenüberstellung besser zur Geltung kommt? Aktuell sind die Kommentare der linken Spalte als Notizen unter den einzelnen Artikeln aufgeführt.

**Comment by cfhaak** [comment]
Prinzipiell ist das natürlich ohne weiteres möglich. Praktisch müsste ich schauen, ob sich eine ökonomische Lösung finden lässt, die sowohl für mich als auch für euch einen dem Ergebnis angemessenen Zeitaufwand erfordert. Ich melde mich.

**Comment by cfhaak** [comment]
Ich glaube der Aufwand wäre wohl eher momentan ungerechtfertig, zumal laut Protokoll prinzipiell entschieden wurde:
a) „Die genaue Position einer Einfügung muss nicht vermerkt werden.“
b) „Kolumnen in den (gedruckten) Dokumenten werden weder dargestellt noch kodiert.“

Ich würde also sagen, dass kommt auf unsere nice-to-have liste, die wir uns ansehen können, falls am Ende des Projekts noch Stunden übrig sind.
