### ISSUE TITLE
Sophia not being able to push documents

### ISSUE THREAD

**Issue by MoHu3** [bundesverfassung-oesterreich/bv-working-data#22]
@sophiakry is not able to push documents after she created divs

Any idea why that is?

**Comment by cfhaak** [comment]
@MoHu3 @sophiakry 
Was genau gibt Oxygen  als Grund an, warum man nicht pushen kann? 
Kann es sein, dass  
a) vor dem Bearbeiten nicht gepullt wurde?
b) jemand anderes parallel an den Dokumenten gearbeitet hat?

Um welche Dokumente geht es?

**Comment by cfhaak** [comment]
Und: wann bist du @sophiakry auf Arbeit?

**Comment by MoHu3** [comment]
Solved it; don‘t really know how but still

**Comment by cfhaak** [comment]
GG @MoHu3 soon will replace all of us technicians ;)
