### ISSUE TITLE
Tanja has no name tag in oxygen

### ISSUE THREAD

**Issue by MoHu3** [bundesverfassung-oesterreich/bv-working-data#23]
Tanja has no name tag in oxygen; could you create one.

**Comment by cfhaak** [comment]
@MoHu3 
You should be able to add people via this table:
https://baserow.acdh-dev.oeaw.ac.at/database/421/table/3049/10970
After adding a person, you'll have to update the xml-Schema, by clicking on the "Run workflow" button at the top right:
https://github.com/bundesverfassung-oesterreich/bv-entities/actions/workflows/update_schema.yml

I already did it :)
