### ISSUE TITLE
Rename file Editions

### ISSUE THREAD

**Issue by nora-zuegel** [bundesverfassung-oesterreich/bv-working-data#5]
Please, dear Fritz, rename the file "Editions" in Oxygen :)
file:/Z:/B-VG%20-%201920/bv-transkribus-export/editions/

**Comment by cfhaak** [comment]
renamed dirs, couldn't test so far, export wf fails, seemingly unrelated, still investigating;
see https://github.com/bundesverfassung-oesterreich/bv-transkribus-export/actions/runs/8082861697/job/22084621895#step:4:28
