### ISSUE TITLE
Problem with Transcribus Text recognition in doc 11

### ISSUE THREAD

**Issue by MoHu3** [bundesverfassung-oesterreich/bv-working-data#7]
in doc 11 on page n. 4 transkribus did not recognize the text of p. 4 but rather of p.5. therefore the text of p.4 is missing in oxygen. fixed the problem in transkribus, however, not sure how do get the recognized text from transkribus into my current oxygen doc.

**Comment by cfhaak** [comment]
Either 
a) wait for a new export from Transkribus and copy it there from the source-xml doc (should be ready I guess)
b) copy the text directly from Transkribus (in which case you will have to encode everything manually)

**Comment by cfhaak** [comment]
@MoHu3 
can we closes this issue?
