### ISSUE TITLE
Problem with second column in doc 13

### ISSUE THREAD

**Issue by MoHu3** [bundesverfassung-oesterreich/bv-working-data#8]
There is a second column in doc 13 including Articles that refer for each article to another doc; need a way to display that reference. 
Right now I just generated a new <p> for every reference at the bottom of the article.

**Comment by cfhaak** [comment]
The Editionsprinzipien.docx I send you a while ago states:
```
Referenzen auf externe Quellen / Intertextualität: Innerhalb der Edierten Dokumente werden 
keine Referenzen auf andere Quellen oder Dokumente kodiert. Einzig der editorische Bericht 
stellt solche Intertextuellen Beziehungen her, referenziert Stellen der edierten Dokumente etc. 
```
So we should encode that like the comments that can be found in the documents from time to time.
The Editionsprinipien state:
```
Kommentare innerhalb der Dokumente, die nicht als Teile des primären edierten Textes 
anzusehen sind, sollen kodiert und dargestellt werden, sofern sie aus fachlicher Sicht als 
relevant gelten.
```

**Comment by cfhaak** [comment]
I'll come up with a way to encode that asap.

**Comment by cfhaak** [comment]
@MoHu3 
According to the current schema I just pushed, this would require a note tag. Read [the documentation](https://bundesverfassung-oesterreich.github.io/bv-schema-framework/#index.xml-body.1_div.4_div.4_div.5) and tell me, what you think of it, regarding the described case.

**Comment by MoHu3** [comment]
Just implemented that accordingly (at least I think so)
